services:
  postgres:
    image: postgres:16
    container_name: veda_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - veda_pgdata:/var/lib/postgresql/data

  client_postgres:
    image: postgres:16
    container_name: veda_client_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${CLIENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CLIENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CLIENT_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - veda_client_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: veda_redis
    ports:
     - "6379:6379"

volumes:  
  veda_pgdata:
  veda_client_pgdata: